/**
 * Created by Purexo on 11/06/2017.
 */
var PARTIE_PHRASE_TIRAGE = [
  [ // 1
    'un zombie',
    'le troll érudit',
    'l\'un des gardiens',
    'un rat mutant',
    'l\'aubergiste',
    'le bourreau ivre',
    'un ménestrel moche',
    'un goblin de ménage',
    'un orque d\'élite',
    'un sorcier stagiaire',
    'un type suscpect',
    'le prisonier barbu',
    'l\'herborsite',
    'le chien d\'un voisin',
    'un garde de la ville',
    'un colporteur',
    'un aventurier',
    'le plombier',
    'l\'ingénieur gobelin',
    'un vieux fou'
  ],
  [ // 2
    'a glissé',
    'a dérapé',
    'a cassé un bidule',
    'a brisé un truc',
    'a vomi',
    'a perdu ses clés',
    'a fait ses besoins',
    'était bloqué',
    's\'est perdu',
    'est tombé',
    's\'est endormi',
    'a passé la nuit',
    's\'est réveillé',
    's\'est tué',
    's\'est fait mal',
    'a trébuché',
    'était coincé',
    's\'est battu',
    'a causé des ennuis',
    'a mis le feu'
  ],
  [ // 3
    'la cave',
    'le souterrain nord',
    'le grenier',
    'mon bureau',
    'la remise à ingrédients',
    'les cuisines',
    'la niche des chiens',
    'la volière à corbeaux',
    'la fosse à scorpions',
    'votre bureau',
    'l\'escalier du deuxième niveau',
    'le bac du limon glaireux',
    'le couloir principal',
    'le hangar de bricolage',
    'l\'atelier de forge',
    'la salle de fouettage',
    'le dortoir des orques',
    'l\'antre du Golbargh',
    'la magasin',
    'votre bibliothèque'
  ],
  [ // 4
    'de cette bête',
    'de cette stupide',
    'd\'une grosse',
    'd\'une infâme',
    'd\'une étrange',
    'd\'une incroyable',
    'de l\'improbable',
    'de la fameuse',
    'de cette imbécile de',
    'de la ridicule',
    'c\'est ballot, de la',
    'de l\'existence d\'une',
    'de l\'embaûche causée par une',
    'du piège que représentait une',
    'de la présence de cette',
    'vous allez rire, d\'une',
    'c\'est bien dommage, de la',
    'de la position d\'une',
    'de son penchant pour une',
    'd\'une médiocre'
  ],
  [ // 5
    'brouette rouillée',
    'manivelle tordue',
    'scie abîmée',
    'bassine oubliée',
    'clé de douze',
    'corbeille de linge',
    'hallebarde tordue',
    'chouette empaillée',
    'terrine piégée',
    'flûte empoisonnée',
    'tête de goule',
    'faux venimeuse',
    'guitare disloquée',
    'bielle biscornue',
    'salière brisée',
    'peau de banane',
    'perruque décrépite',
    'chaussette rouge',
    'babouche verte',
    'pantoufle usée'
  ],
  [ // 6
    'venait de ma grand-mère',
    'était justement là',
    'est apparue comme par magie',
    'venait de votre cousin',
    'avait été abandonnée',
    'était suscpecte',
    'n\'aurait pas dû se trouver là',
    'avait justement l\'air fourbe',
    'était dans l\'ombre',
    'n\'avait l\'air de rien',
    'a été laissée par un voisin',
    'était bel et bien dangereuse',
    'était pourtant chère',
    'avait une odeur inquiétante',
    'avait changé de place',
    'aurait dû être rangée',
    'vous appartient',
    's\'est révélée glissante',
    'était peut-être à moi',
    'pose toujours des problèmes'
  ]
];